const FETCH_DAILY_SELL_TRANSACTIONS = "FETCH_DAILY_SELL_TRANSACTIONS";
const SHOW_DAILY_SELL_TRANSACTIONS = "SHOW_DAILY_SELL_TRANSACTIONS";
const FETCH_DAILY_SELLS = "FETCH_DAILY_SELLS";
const DELETE_SELL_ACTION = "DELETE_SELL_ACTION";
const REMOVE_SELL_ACTION = "REMOVE_SELL_ACTION";
const SHOW_DAILY_SELLS = "SHOW_DAILY_SELLS";
const SHOW_DAILY_SELL_TRANSACTIONS_ERROR = "SHOW_DAILY_SELL_TRANSACTIONS_ERROR";
const FETCH_TOTAL_LOAN_PAYMENTS_ON_DATE = "FETCH_TOTAL_LOAN_PAYMENTS_ON_DATE";
const SET_TOTAL_LOAN_PAYMENTS_ON_DATE = "SET_TOTAL_LOAN_PAYMENTS_ON_DATE";

export const DAILY_ACTIONS = {
    FETCH_DAILY_SELL_TRANSACTIONS,
    SHOW_DAILY_SELL_TRANSACTIONS,
    SHOW_DAILY_SELL_TRANSACTIONS_ERROR,
    FETCH_TOTAL_LOAN_PAYMENTS_ON_DATE,
    SET_TOTAL_LOAN_PAYMENTS_ON_DATE,
    FETCH_DAILY_SELLS,
    SHOW_DAILY_SELLS,
    DELETE_SELL_ACTION,
    REMOVE_SELL_ACTION,
}
