const FETCH_TODAYS_ITEM_SELL_ACTION = "FETCH_TODAYS_ITEM_SELL_ACTION";
const SHOW_TODAYS_ITEM_SELL_ACTION = "SHOW_TODAYS_ITEM_SELL_ACTION";
const SHOW_TODAYS_ITEM_SELL_ERROR_ACTION = "SHOW_TODAYS_ITEM_SELL_ERROR_ACTION";

const FETCH_LOANS_GIVEN_ACTION = "FETCH_LOANS_GIVEN_ACTION";
const SHOW_LOANS_GIVEN_ACTION = "SHOW_LOANS_GIVEN_ACTION";
const SHOW_LOANS_GIVEN_ERROR_ACTION = "SHOW_LOANS_GIVEN_ERROR_ACTION";

const FETCH_LOANS_PAID_ACTION = "FETCH_LOANS_PAID_ACTION";
const SHOW_LOANS_PAID_ACTION = "SHOW_LOANS_PAID_ACTION";
const SHOW_LOANS_PAID_ERROR_ACTION = "SHOW_LOANS_PAID_ERROR_ACTION";

export const HOME_ACTIONS = {
    FETCH_TODAYS_ITEM_SELL_ACTION,
    SHOW_TODAYS_ITEM_SELL_ACTION,
    SHOW_TODAYS_ITEM_SELL_ERROR_ACTION,
    FETCH_LOANS_GIVEN_ACTION,
    SHOW_LOANS_GIVEN_ACTION,
    SHOW_LOANS_GIVEN_ERROR_ACTION,
    FETCH_LOANS_PAID_ACTION,
    SHOW_LOANS_PAID_ACTION,
    SHOW_LOANS_PAID_ERROR_ACTION,

}
