const FETCH_ITEM_ACTION = "FETCH_ITEM_ACTION";
const SHOW_ITEM_DETAIL_ACTION = "SHOW_ITEM_DETAIL_ACTION";
const SHOW_ITEM_ERROR_ACTION = "SHOW_ITEM_ERROR_ACTION";
const SAVE_ITEM_ACTION = "SAVE_ITEM_ACTION";
const ADD_ITEM_ACTION = "ADD_ITEM_ACTION";
const DELETE_ITEM_ACTION = "DELETE_ITEM_ACTION";
const REMOVE_ITEM_ACTION = "REMOVE_ITEM_ACTION";
const EDIT_ITEM_ACTION = "EDIT_ITEM_ACTION";
const UPDATE_ITEM_ACTION = "UPDATE_ITEM_ACTION";

export const ITEM_ACTIONS = {
    FETCH_ITEM_ACTION,
    SHOW_ITEM_DETAIL_ACTION,
    SHOW_ITEM_ERROR_ACTION, 
    SAVE_ITEM_ACTION,
    ADD_ITEM_ACTION,
    DELETE_ITEM_ACTION,
    REMOVE_ITEM_ACTION,
    EDIT_ITEM_ACTION,
    UPDATE_ITEM_ACTION
}

const FETCH_ITEM_CATEGORIES_ACTION = "FETCH_ITEM_CATEGORIES_ACTION";
const SHOW_ITEM_CATEGORIES_ACTION = "SHOW_ITEM_CATEGORIES_ACTION"; 
const SHOW_ITEM_CATEGORIES_ERROR_ACTION = "SHOW_ITEM_CATEGORIES_ERROR_ACTION"; 
const SAVE_ITEM_CATEGORY_ACTION = "SAVE_ITEM_CATEGORY_ACTION";
const ADD_ITEM_CATEGORY_ACTION = "ADD_ITEM_CATEGORY_ACTION";
const DELETE_ITEM_CATEGORY_ACTION = "DELETE_ITEM_CATEGORY_ACTION";
const REMOVE_ITEM_CATEGORY_ACTION = "REMOVE_ITEM_CATEGORY_ACTION";

export const ITEM_CATEGORIES_ACTIONS = {
    FETCH_ITEM_CATEGORIES_ACTION,
    SHOW_ITEM_CATEGORIES_ACTION, 
    SHOW_ITEM_CATEGORIES_ERROR_ACTION,
    SAVE_ITEM_CATEGORY_ACTION,
    ADD_ITEM_CATEGORY_ACTION,
    DELETE_ITEM_CATEGORY_ACTION,
    REMOVE_ITEM_CATEGORY_ACTION
}

const FETCH_UNITS_ACTION = "FETCH_UNITS_ACTION";
const SHOW_UNITS_ACTION = "SHOW_UNITS_ACTION";
const SAVE_UNIT_ACTION = "SAVE_UNIT_ACTION";
const ADD_UNIT_ACTION = "ADD_UNIT_ACTION";
const DELETE_UNIT_ACTION = "DELETE_UNIT_ACTION";
const REMOVE_UNIT_ACTION = "REMOVE_UNIT_ACTION";

export const UNITS_ACTION = {
    FETCH_UNITS_ACTION,
    SHOW_UNITS_ACTION,
    SAVE_UNIT_ACTION,
    ADD_UNIT_ACTION,
    DELETE_UNIT_ACTION,
    REMOVE_UNIT_ACTION
}