const FETCH_DAILY_ITEM_TRANSACTIONS_ACTION = "FETCH_DAILY_ITEM_TRANSACTIONS_ACTION";
const SHOW_DAILY_ITEM_TRANSACTIONS_ACTION = "SHOW_DAILY_ITEM_TRANSACTIONS_ACTION";
const SHOW_DAILY_ITEM_TRANSACTIONS_ERROR_ACTION = "SHOW_DAILY_ITEM_TRANSACTIONS_ERROR_ACTION";

const FETCH_WEEKLY_ITEM_TRANSACTIONS_ACTION = "FETCH_WEEKLY_ITEM_TRANSACTIONS_ACTION";
const SHOW_WEEKLY_ITEM_TRANSACTIONS_ACTION = "SHOW_WEEKLY_ITEM_TRANSACTIONS_ACTION";
const SHOW_WEEKLY_ITEM_TRANSACTIONS_ERROR_ACTION = "SHOW_WEEKLY_ITEM_TRANSACTIONS_ERROR_ACTION";
 
const FETCH_MONTHLY_ITEM_TRANSACTIONS_ACTION = "FETCH_MONTHLY_ITEM_TRANSACTIONS_ACTION";
const SHOW_MONTHLY_ITEM_TRANSACTIONS_ACTION = "SHOW_MONTHLY_ITEM_TRANSACTIONS_ACTION";

 export const ITEM_TRANSACTION_ACTIONS = {
    FETCH_DAILY_ITEM_TRANSACTIONS_ACTION,
    SHOW_DAILY_ITEM_TRANSACTIONS_ACTION,
    SHOW_DAILY_ITEM_TRANSACTIONS_ERROR_ACTION,

    FETCH_WEEKLY_ITEM_TRANSACTIONS_ACTION,
    SHOW_WEEKLY_ITEM_TRANSACTIONS_ACTION,
    SHOW_WEEKLY_ITEM_TRANSACTIONS_ERROR_ACTION,
    
    FETCH_MONTHLY_ITEM_TRANSACTIONS_ACTION,
    SHOW_MONTHLY_ITEM_TRANSACTIONS_ACTION
 }