const FETCH_STOCK_ACTION = "FETCH_STOCK_ACTION";
const FETCH_TRANSACTIONS_ACTION = "FETCH_TRANSACTIONS_ACTION";
const SHOW_TRANSACTIONS_ACTION = "SHOW_TRANSACTIONS_ACTION";
const SHOW_STOCK_DETAIL_ACTION = "SHOW_STOCK_DETAIL_ACTION";
const SHOW_STOCK_ERROR_ACTION = "SHOW_STOCK_ERROR_ACTION";
const SAVE_STOCK_ACTION = "SAVE_STOCK_ACTION";
const ADD_STOCK_ACTION = "ADD_STOCK_ACTION";
const DELETE_STOCK_ACTION = "DELETE_STOCK_ACTION";
const REMOVE_STOCK_ACTION = "REMOVE_STOCK_ACTION";
const SAVE_NEW_TRANSACTION_ACTION = "SAVE_NEW_TRANSACTION_ACTION";
const ADD_NEW_TRANSACTION_ACTION = "ADD_NEW_TRANSACTION_ACTION";

export const STOCK_ACTIONS = {
    FETCH_STOCK_ACTION,
    FETCH_TRANSACTIONS_ACTION,
    SHOW_TRANSACTIONS_ACTION,
    SHOW_STOCK_DETAIL_ACTION,
    SHOW_STOCK_ERROR_ACTION, 
    SAVE_STOCK_ACTION,
    ADD_STOCK_ACTION,
    DELETE_STOCK_ACTION,
    REMOVE_STOCK_ACTION,
    SAVE_NEW_TRANSACTION_ACTION,
    ADD_NEW_TRANSACTION_ACTION
}