const FETCH_USERS_ACTION = "FETCH_USERS_ACTION";
const SHOW_USERS_ACTION = "SHOW_USERS_ACTION";
const SHOW_USERS_ERROR_ACTION = "SHOW_USERS_ERROR_ACTION";
const SAVE_NEW_USER_TO_DB_ACTION = "SAVE_NEW_USER_TO_DB_ACTION";
const ADD_NEW_USER_ACTION = "ADD_NEW_USER_ACTION";
const SAVE_EDIT_USER_ACTION = "SAVE_EDIT_USER_ACTION";
const SHOW_EDIT_USER_MODAL_ACTION = "SHOW_EDIT_USER_MODAL_ACTION";
const HIDE_EDIT_USER_MODAL_ACTION = "HIDE_EDIT_USER_MODAL_ACTION";
const DELETE_USER_ACTION = "DELETE_USER_ACTION";
const DELETE_USER_SUCCESS_ACTION = "DELETE_USER_SUCCESS_ACTION";

export const USER_ACTIONS = {
    FETCH_USERS_ACTION,
    SHOW_USERS_ACTION,
    SHOW_USERS_ERROR_ACTION,
    SAVE_NEW_USER_TO_DB_ACTION,
    ADD_NEW_USER_ACTION,
    SAVE_EDIT_USER_ACTION,
    SHOW_EDIT_USER_MODAL_ACTION,
    HIDE_EDIT_USER_MODAL_ACTION,
    DELETE_USER_ACTION,
    DELETE_USER_SUCCESS_ACTION
}
